name = "EpicastPlot"
uuid = "52eb2dcd-e8c2-4d04-b5a6-dad7aa2a568e"
authors = ["Scottie Alexander <palexander@lanl.gov>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Epicast = "13025778-9818-4194-93df-7c384e58662e"
EpicastTables = "82061bd3-70b2-4a0b-b6e0-11568b5e14b8"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[compat]
Colors = "0.13.1"
PyPlot = "2.11.6"
