name = "EpicastGeoplot"
uuid = "70547f8d-9786-49f1-9a56-455c94cda6e0"
authors = ["Scottie Alexander <palexander@lanl.gov>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Epicast = "13025778-9818-4194-93df-7c384e58662e"
EpicastTables = "82061bd3-70b2-4a0b-b6e0-11568b5e14b8"
Inflate = "d25df0c9-e2be-5dd7-82c8-3ad0b3e990b9"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"

[compat]
Colors = "0.13.1"
Dates = "1.11.0"
Epicast = "0.1.0"
EpicastTables = "0.1.0"
Inflate = "0.1.5"
LibGit2 = "1.11.0"
Pkg = "1.11.0"
Printf = "1.11.0"
PyCall = "1.96.4"
PyPlot = "2.11.6"
Shapefile = "0.13.2"
Statistics = "1.11.1"
Tar = "1.10.0"
